### ISSUE TITLE
windows support / targets really included?

### ISSUE THREAD

**Issue by fommil** [etsy/sbt-compile-quick-plugin#3]
Thanks for this plugin! I've just found it and I think it could work well combined with https://github.com/fommil/sbt-big-project

I have to use Windows at work and the autocompletion doesn't work. Looks like you're assuming `/` as the first character. Can you make this perhaps work with relative paths wrt the source directory base? e.g. `compileQuick my/domain/MyClass.scala`

**Comment by fommil** [comment]
I just tried this out by deleting the `.class` files that I expected a `.scala` file to create, then doing `myproj/compileQuick d:/full/path/to/file.scala` and ... nothing. No files appeared in the target directory. Was it supposed to do something?

**Comment by fommil** [comment]
oh, it works by relative path. I typed `myproj/compileQuick to/file.scala` and it tried to compile it, but it failed with missing packages and classes and pretty much everything. Are you passing in the target directory as a classpath folder? Because otherwise this plugin will only work for files that are completely independent of classes and packages in the current project.

**Comment by fommil** [comment]
Once we can fix these problems, I'd be keen on creating an ENSIME command to do this :smile:

**Comment by ajsquared** [comment]
The autocompletion gets its targets from the value of `scalaSource`.  I think it would be possible to strip off the base directory from that - I'll have to look and see if there was any reason that wasn't done originally.

Specifying an absolute path didn't work for you as the check for an absolute path assumes it will start with a '/' which isn't true for windows.  A better check would be for paths starting with the base path for source files and prepending that if not present.

The behavior you saw with the missing packages/classes is the expected behavior in its current state.  This came out of a fairly specific use case we had for compiling single files that did not depend on anything else in the current project.  For other cases we've generally just relied on the built-in incremental compilation.

I can see adding the target directory for the current project to the classpath, but I'm unsure if that would result in any unexpected behavior.  This uses some internal SBT APIs which haven't been the most friendly.  We can certainly try and see what happens!

**Comment by ajsquared** [comment]
I'm going to split this into a couple separate issues to better track the various issues you've noted separately.

If you're interested we'd be happy to accept contributions from you on them!

**Comment by fommil** [comment]
hehe, just reading the source and making the same conclusions :smile:

adding the target definitely will have unexpected consequences, so I think it's a feature only for people who know what they are doing, and @propensive :stuck_out_tongue_winking_eye: 

I'm on holidays in a few days and currently fighting some really epic bugs in the scala compiler https://issues.scala-lang.org/browse/SI-9683 and sbt https://github.com/sbt/sbt/issues/2496 so I'm unlikely to get to this anytime soon, but the fixes I'm keen on look pretty trivial to implement so when I decide to do this I can send something. I might just hack something together for my build. I am happy using emacs to do the completion, and I'd be keen on deleting the quickPackage incase it conflicts with sbt-big-project

**Comment by ajsquared** [comment]
Do you think it's reasonable to add a configuration setting to enable adding the target directory to the classpath?

We use packageQuick fairly extensively internally and wouldn't be able to have it removed.  What is the conflict with sbt-big-project?  If its just a name conflict renaming would be okay.

**Comment by fommil** [comment]
quick hack for a quick compile. Won't handle canonicalisation or case insensitivity correctly, but it seems to do the trick!

(I really hate the macro stuff... if you want to see how to rewrite as an old fashioned piece of scala, have a look at sbt-big-project. It makes it clearer what is happening when. Hint: everything `.value` is evaluated before your code runs, even if its in an `if` statement :wink: )

``` scala
    Def.inputTask {
      val input = parser.parsed.replace("\\", "/")
      val path = (scalaSource in conf).value.getAbsolutePath.replace("\\", "/")
      val fileToCompile = if (input.startsWith(path)) file(input) else file(path) / input
      val log = streams.value.log

      if (fileToCompile.exists) {
        val compilers = Keys.compilers.value
        IO.createDirectory(outputDir.value)
        log.info(s"Compiling $fileToCompile")

        val cp = outputDir.value +: classpath.value.map(_.data)
        compilers.scalac(Seq(fileToCompile), noChanges, cp, outputDir.value, options.value, noopCallback, maxErrors, inputs.value.incSetup.cache, log)
      } else {
        log.warn(s"File doesn't exist: $fileToCompile")
      }
    }
```

**Comment by fommil** [comment]
maybe a regex is better than checking the stem.

**Comment by fommil** [comment]
btw, to automate Windows testing please see `ensime-sbt` for inspiration.

**Comment by fommil** [comment]
Oh it's even easier that that. Just check if `file(input)` exists, if not add the directory and check existence. Warning message could include just the input name. Perhaps a future upgrade could check all source directories for a match.

**Comment by fommil** [comment]
@ajsquared I think we'll add a much more minimal version of the compile-quick command into ensime-sbt since we don't need the parsing or anything. Thanks for the idea!

**Comment by ajsquared** [comment]
Cool, that sounds good!

I've pulled some of the general improvements from this thread into separate issues and will close this one.
